vich_uploader:
    db_driver: orm

    metadata:
        type: attribute
        
    #config vich pour l'upload d'images    
    mappings:
        recipe_images:
            uri_prefix: /images/restaurant
            upload_destination: '%kernel.project_dir%/public/images/restaurant'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer